package bean;
// Generated 30/11/2023 20:03:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClienteFgv generated by hbm2java
 */
@Entity
@Table(name="cliente_fgv"
    ,catalog="db_felipe_ronceti"
)
public class ClienteFgv  implements java.io.Serializable {


     private int idclienteFgv;
     private String nomeFgv;
     private String cpfFgv;
     private String rgFgv;
     private String cepFgv;
     private String enderecoFgv;
     private String telefoneFgv;
     private String bairroFgv;
     private String estadocivilFgv;
     private String sexoFgv;
     private String apelidoFgv;
     private String cnpjFgv;
     private String emailFgv;
     private String ufFgv;
     private String nacionalidadeFgv;
     private String clienteFgvcol;

    public ClienteFgv() {
    }

    public ClienteFgv(int idclienteFgv, String nomeFgv, String cpfFgv, String rgFgv, String cepFgv, String enderecoFgv, String telefoneFgv, String bairroFgv, String estadocivilFgv, String sexoFgv, String apelidoFgv, String cnpjFgv, String emailFgv, String ufFgv, String nacionalidadeFgv, String clienteFgvcol) {
       this.idclienteFgv = idclienteFgv;
       this.nomeFgv = nomeFgv;
       this.cpfFgv = cpfFgv;
       this.rgFgv = rgFgv;
       this.cepFgv = cepFgv;
       this.enderecoFgv = enderecoFgv;
       this.telefoneFgv = telefoneFgv;
       this.bairroFgv = bairroFgv;
       this.estadocivilFgv = estadocivilFgv;
       this.sexoFgv = sexoFgv;
       this.apelidoFgv = apelidoFgv;
       this.cnpjFgv = cnpjFgv;
       this.emailFgv = emailFgv;
       this.ufFgv = ufFgv;
       this.nacionalidadeFgv = nacionalidadeFgv;
       this.clienteFgvcol = clienteFgvcol;
    }
   
     @Id 

    
    @Column(name="idcliente_fgv", unique=true, nullable=false)
    public int getIdclienteFgv() {
        return this.idclienteFgv;
    }
    
    public void setIdclienteFgv(int idclienteFgv) {
        this.idclienteFgv = idclienteFgv;
    }

    
    @Column(name="nome_fgv", nullable=false, length=20)
    public String getNomeFgv() {
        return this.nomeFgv;
    }
    
    public void setNomeFgv(String nomeFgv) {
        this.nomeFgv = nomeFgv;
    }

    
    @Column(name="cpf_fgv", nullable=false, length=15)
    public String getCpfFgv() {
        return this.cpfFgv;
    }
    
    public void setCpfFgv(String cpfFgv) {
        this.cpfFgv = cpfFgv;
    }

    
    @Column(name="rg_fgv", nullable=false, length=30)
    public String getRgFgv() {
        return this.rgFgv;
    }
    
    public void setRgFgv(String rgFgv) {
        this.rgFgv = rgFgv;
    }

    
    @Column(name="cep_fgv", nullable=false, length=10)
    public String getCepFgv() {
        return this.cepFgv;
    }
    
    public void setCepFgv(String cepFgv) {
        this.cepFgv = cepFgv;
    }

    
    @Column(name="endereco_fgv", nullable=false, length=60)
    public String getEnderecoFgv() {
        return this.enderecoFgv;
    }
    
    public void setEnderecoFgv(String enderecoFgv) {
        this.enderecoFgv = enderecoFgv;
    }

    
    @Column(name="telefone_fgv", nullable=false, length=14)
    public String getTelefoneFgv() {
        return this.telefoneFgv;
    }
    
    public void setTelefoneFgv(String telefoneFgv) {
        this.telefoneFgv = telefoneFgv;
    }

    
    @Column(name="bairro_fgv", nullable=false, length=100)
    public String getBairroFgv() {
        return this.bairroFgv;
    }
    
    public void setBairroFgv(String bairroFgv) {
        this.bairroFgv = bairroFgv;
    }

    
    @Column(name="estadocivil_fgv", nullable=false, length=20)
    public String getEstadocivilFgv() {
        return this.estadocivilFgv;
    }
    
    public void setEstadocivilFgv(String estadocivilFgv) {
        this.estadocivilFgv = estadocivilFgv;
    }

    
    @Column(name="sexo_fgv", nullable=false, length=15)
    public String getSexoFgv() {
        return this.sexoFgv;
    }
    
    public void setSexoFgv(String sexoFgv) {
        this.sexoFgv = sexoFgv;
    }

    
    @Column(name="apelido_fgv", nullable=false, length=50)
    public String getApelidoFgv() {
        return this.apelidoFgv;
    }
    
    public void setApelidoFgv(String apelidoFgv) {
        this.apelidoFgv = apelidoFgv;
    }

    
    @Column(name="cnpj_fgv", nullable=false, length=18)
    public String getCnpjFgv() {
        return this.cnpjFgv;
    }
    
    public void setCnpjFgv(String cnpjFgv) {
        this.cnpjFgv = cnpjFgv;
    }

    
    @Column(name="email_fgv", nullable=false, length=80)
    public String getEmailFgv() {
        return this.emailFgv;
    }
    
    public void setEmailFgv(String emailFgv) {
        this.emailFgv = emailFgv;
    }

    
    @Column(name="uf_fgv", nullable=false, length=15)
    public String getUfFgv() {
        return this.ufFgv;
    }
    
    public void setUfFgv(String ufFgv) {
        this.ufFgv = ufFgv;
    }

    
    @Column(name="nacionalidade_fgv", nullable=false, length=45)
    public String getNacionalidadeFgv() {
        return this.nacionalidadeFgv;
    }
    
    public void setNacionalidadeFgv(String nacionalidadeFgv) {
        this.nacionalidadeFgv = nacionalidadeFgv;
    }

    
    @Column(name="cliente_fgvcol", nullable=false, length=45)
    public String getClienteFgvcol() {
        return this.clienteFgvcol;
    }
    
    public void setClienteFgvcol(String clienteFgvcol) {
        this.clienteFgvcol = clienteFgvcol;
    }




}


