package bean;
// Generated 30/11/2023 20:03:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompraFgv generated by hbm2java
 */
@Entity
@Table(name="compra_fgv"
    ,catalog="db_felipe_ronceti"
)
public class CompraFgv  implements java.io.Serializable {


     private int idcompraFgv;
     private String nomeclienteFgv;
     private String valorcompraFgv;
     private String quantidadeFgv;
     private String statusFgv;
     private int idvendedorFgv;
     private int idclienteFgv;
    public CompraFgv() {
    }

    public CompraFgv(int idcompraFgv,int idclienteFgv, int idvendedorFgv,  String nomeclienteFgv, String valorcompraFgv, String quantidadeFgv, String statusFgv) {
       this.idcompraFgv = idcompraFgv;
       this.idclienteFgv = idclienteFgv;
       this.idvendedorFgv = idvendedorFgv;
       this.nomeclienteFgv = nomeclienteFgv;
       this.valorcompraFgv = valorcompraFgv;
       this.quantidadeFgv = quantidadeFgv;
       this.statusFgv = statusFgv;
    }
   
     @Id 

    
    @Column(name="idcompra_fgv", unique=true, nullable=false)
    public int getIdcompraFgv() {
        return this.idcompraFgv;
    }
    
    public void setIdcompraFgv(int idcompraFgv) {
        this.idcompraFgv = idcompraFgv;
    }
    
    @Column(name="idcliente_fgv", unique=true, nullable=false)
    public int getIdclienteFgv() {
        return this.idclienteFgv;
    }
    
    public void setIdclienteFgv(int idclienteFgv) {
        this.idclienteFgv = idclienteFgv;
    }
    
      @Column(name="idvendedor_fgv", unique=true, nullable=false)
    public int getIdvendedorFgv() {
        return this.idvendedorFgv;
    }
    
    public void setIdvendedorFgv(int idvendedorFgv) {
        this.idvendedorFgv = idvendedorFgv;
    }
    
    @Column(name="nomecliente_fgv", nullable=false, length=45)
    public String getNomeclienteFgv() {
        return this.nomeclienteFgv;
    }
    
    public void setNomeclienteFgv(String nomeclienteFgv) {
        this.nomeclienteFgv = nomeclienteFgv;
    }

    
    @Column(name="valorcompra_fgv", nullable=false, precision=8)
    public String getValorcompraFgv() {
        return this.valorcompraFgv;
    }
    
    public void setValorcompraFgv(String valorcompraFgv) {
        this.valorcompraFgv = valorcompraFgv;
    }

    
    @Column(name="quantidade_fgv", nullable=false)
    public String getQuantidadeFgv() {
        return this.quantidadeFgv;
    }
    
    public void setQuantidadeFgv(String quantidadeFgv) {
        this.quantidadeFgv = quantidadeFgv;
    }

    
    @Column(name="status_fgv", nullable=false, length=45)
    public String getStatusFgv() {
        return this.statusFgv;
    }
    
    public void setStatusFgv(String statusFgv) {
        this.statusFgv = statusFgv;
    }




}


