package bean;
// Generated 30/11/2023 20:03:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompraprodutoFgv generated by hbm2java
 */
@Entity
@Table(name="compraproduto_fgv"
    ,catalog="db_felipe_ronceti"
)
public class CompraprodutoFgv  implements java.io.Serializable {


     private int idcompraprodutoFgv;
     private int compraFgv;
     private int produtoFgv;
     private BigDecimal valorcompraprodutoFgv;
     private String quantidadeFgv;
     private String nomeprodutoFgv;

    public CompraprodutoFgv() {
    }

    public CompraprodutoFgv(int idcompraprodutoFgv, int compraFgv, int produtoFgv, BigDecimal valorcompraprodutoFgv, String quantidadeFgv, String nomeprodutoFgv) {
       this.idcompraprodutoFgv = idcompraprodutoFgv;
       this.compraFgv = compraFgv;
       this.produtoFgv = produtoFgv;
       this.valorcompraprodutoFgv = valorcompraprodutoFgv;
       this.quantidadeFgv = quantidadeFgv;
       this.nomeprodutoFgv = nomeprodutoFgv;
    }
   
        public static void main(String[] args) {
        List<CompraprodutoFgv> listProdutos = new ArrayList<>();

        CompraprodutoFgv produto1 = new CompraprodutoFgv(1, 101, 201, new BigDecimal("10.50"), "2", "Product1");
        CompraprodutoFgv produto2 = new CompraprodutoFgv(2, 102, 202, new BigDecimal("20.75"), "3", "Product2");

        listProdutos.add(produto1);
        listProdutos.add(produto2);

    }


     @Id 

    
    @Column(name="idcompraproduto_fgv", unique=true, nullable=false)
    public int getIdcompraprodutoFgv() {
        return this.idcompraprodutoFgv;
    }
    
    public void setIdcompraprodutoFgv(int idcompraprodutoFgv) {
        this.idcompraprodutoFgv = idcompraprodutoFgv;
    }

    
    @Column(name="compra_fgv", nullable=false)
    public int getCompraFgv() {
        return this.compraFgv;
    }
    
    public void setCompraFgv(int compraFgv) {
        this.compraFgv = compraFgv;
    }

    
    @Column(name="produto_fgv", nullable=false)
    public int getProdutoFgv() {
        return this.produtoFgv;
    }
    
    public void setProdutoFgv(int produtoFgv) {
        this.produtoFgv = produtoFgv;
    }

    
    @Column(name="valorcompraproduto_fgv", nullable=false, precision=10)
    public BigDecimal getValorcompraprodutoFgv() {
        return this.valorcompraprodutoFgv;
    }
    
    public void setValorcompraprodutoFgv(BigDecimal valorcompraprodutoFgv) {
        this.valorcompraprodutoFgv = valorcompraprodutoFgv;
    }

    
    @Column(name="quantidade_fgv", nullable=false, length=10)
    public String getQuantidadeFgv() {
        return this.quantidadeFgv;
    }
    
    public void setQuantidadeFgv(String quantidadeFgv) {
        this.quantidadeFgv = quantidadeFgv;
    }

    
    @Column(name="nomeproduto_fgv", nullable=false, length=45)
    public String getNomeprodutoFgv() {
        return this.nomeprodutoFgv;
    }
    
    public void setNomeprodutoFgv(String nomeprodutoFgv) {
        this.nomeprodutoFgv = nomeprodutoFgv;
    }




}


