package bean;
// Generated 18/12/2023 10:00:26 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraFgv generated by hbm2java
 */
@Entity
@Table(name = "compra_fgv",
        catalog = "db_felipe_ronceti"
)
public class CompraFgv implements java.io.Serializable {

    private int idcompraFgv;
    private ClienteFgv clienteFgv;
    private VendedorFgv vendedorFgv;
    private Date datadaCompraFgv;
    private double valorTotalFgv;

    public CompraFgv() {
    }

    public CompraFgv(int idcompraFgv, ClienteFgv clienteFgv, VendedorFgv vendedorFgv, Date datadaCompraFgv, double valorTotalFgv) {
        this.idcompraFgv = idcompraFgv;
        this.clienteFgv = clienteFgv;
        this.vendedorFgv = vendedorFgv;
        this.datadaCompraFgv = datadaCompraFgv;
        this.valorTotalFgv = valorTotalFgv;
    }

    @Id

    @Column(name = "idcompra_fgv", unique = true, nullable = false)
    public int getIdcompraFgv() {
        return this.idcompraFgv;
    }

    public void setIdcompraFgv(int idcompraFgv) {
        this.idcompraFgv = idcompraFgv;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_cliente_fgv", nullable = false)
    public ClienteFgv getClienteFgv() {
        return this.clienteFgv;
    }

    public void setClienteFgv(ClienteFgv clienteFgv) {
        this.clienteFgv = clienteFgv;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_vendedor_fgv", nullable = false)
    public VendedorFgv getVendedorFgv() {
        return this.vendedorFgv;
    }

    public void setVendedorFgv(VendedorFgv vendedorFgv) {
        this.vendedorFgv = vendedorFgv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datadaCompra_fgv", nullable = false, length = 10)
    public Date getDatadaCompraFgv() {
        return this.datadaCompraFgv;
    }

    public void setDatadaCompraFgv(Date datadaCompraFgv) {
        this.datadaCompraFgv = datadaCompraFgv;
    }

    @Column(name = "valorTotal_fgv", nullable = false, precision = 10)
    public double getValorTotalFgv() {
        return this.valorTotalFgv;
    }

    public void setValorTotalFgv(double valorTotalFgv) {
        this.valorTotalFgv = valorTotalFgv;
    }

}
