package bean;
// Generated 30/11/2023 20:03:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VendedorFgv generated by hbm2java
 */
@Entity
@Table(name="vendedor_fgv"
    ,catalog="db_felipe_ronceti"
)
public class VendedorFgv  implements java.io.Serializable {


     private int idvendedorFgv;
     private String nomeFgv;
     private String cpfFgv;
     private String telefoneFgv;
     private String emailFgv;

    public VendedorFgv() {
    }

    public VendedorFgv(int idvendedorFgv, String nomeFgv, String cpfFgv, String telefoneFgv, String emailFgv) {
       this.idvendedorFgv = idvendedorFgv;
       this.nomeFgv = nomeFgv;
       this.cpfFgv = cpfFgv;
       this.telefoneFgv = telefoneFgv;
       this.emailFgv = emailFgv;
    }
   
     @Id 

    
    @Column(name="idvendedor_fgv", unique=true, nullable=false)
    public int getIdvendedorFgv() {
        return this.idvendedorFgv;
    }
    
    public void setIdvendedorFgv(int idvendedorFgv) {
        this.idvendedorFgv = idvendedorFgv;
    }

    
    @Column(name="nome_fgv", nullable=false, length=20)
    public String getNomeFgv() {
        return this.nomeFgv;
    }
    
    public void setNomeFgv(String nomeFgv) {
        this.nomeFgv = nomeFgv;
    }

    
    @Column(name="cpf_fgv", nullable=false, length=15)
    public String getCpfFgv() {
        return this.cpfFgv;
    }
    
    public void setCpfFgv(String cpfFgv) {
        this.cpfFgv = cpfFgv;
    }

    
    @Column(name="telefone_fgv", nullable=false, length=14)
    public String getTelefoneFgv() {
        return this.telefoneFgv;
    }
    
    public void setTelefoneFgv(String telefoneFgv) {
        this.telefoneFgv = telefoneFgv;
    }

    
    @Column(name="email_fgv", nullable=false, length=18)
    public String getEmailFgv() {
        return this.emailFgv;
    }
    
    public void setEmailFgv(String emailFgv) {
        this.emailFgv = emailFgv;
    }




}


